import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import animate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/features/**/*.{ts,tsx}",
    "./public/imported-screens/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        foreground: "hsl(var(--foreground))",
        "on-error": "#ffffff",
        "secondary-container": "#9bf6ba",
        "inverse-primary": "#ffb4a2",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#9dcaff",
        "on-surface-variant": "#5b403a",
        outline: "#907068",
        "inverse-on-surface": "#ffede9",
        "on-tertiary-fixed-variant": "#00497b",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#ffb4a2",
        "tertiary-container": "#0078c6",
        "tertiary-fixed": "#d1e4ff",
        "surface-dim": "#f1d4cd",
        "surface-variant": "#fadcd5",
        "on-tertiary-container": "#fdfcff",
        "surface-tint": "#b42800",
        background: "#fff8f6",
        surface: "#fff8f6",
        "primary-container": "#d8390e",
        "on-background": "#271814",
        "secondary-fixed-dim": "#80d9a0",
        "outline-variant": "#e4beb5",
        "on-secondary-container": "#0e7344",
        "secondary-fixed": "#9bf6ba",
        "on-primary-fixed": "#3c0700",
        tertiary: "#005f9e",
        "on-secondary-fixed-variant": "#00522e",
        "on-primary": "#ffffff",
        "surface-bright": "#fff8f6",
        "on-primary-fixed-variant": "#8a1c00",
        "surface-container-high": "#ffe2db",
        "surface-container-low": "#fff1ed",
        "error-container": "#ffdad6",
        secondary: "#006d3f",
        "primary-fixed": "#ffdad2",
        "on-secondary-fixed": "#00210f",
        "surface-container": "#ffe9e4",
        "on-primary-container": "#fffbff",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "surface-container-highest": "#fadcd5",
        "inverse-surface": "#3e2c28",
        "on-surface": "#271814",
        "on-error-container": "#93000a",
        primary: "#b02700",
        "on-tertiary-fixed": "#001d35",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        "margin-desktop": "40px",
        base: "4px",
        "margin-mobile": "16px",
        xl: "32px",
        gutter: "16px",
        xxl: "48px",
        lg: "24px",
        xs: "8px",
        md: "16px",
      },
      fontFamily: {
        display: ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "label-md": ["DM Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["DM Sans", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "code-otp": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "code-otp": ["24px", { lineHeight: "32px", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      boxShadow: {
        soft: "0 18px 50px rgba(44, 44, 58, 0.10)",
        card: "0 2px 12px rgba(44, 44, 58, 0.08)",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 180ms ease-out both",
      },
    },
  },
  plugins: [forms, animate],
};

export default config;
